# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXoOZduxljYZks66B9RC6vJ_BmrPYPu3
"""

import streamlit as st
import json
import os
import tempfile
from datetime import date
from google import genai
from google.oauth2 import service_account

from layer1_perception import run_session
from layer2_aggregation import run_aggregation
from layer3_reasoner    import run_layer3

st.set_page_config(page_title="Progress Proof", layout="wide")

from taxonomy import STAGE_TAXONOMY

STATUS_STYLE = {
    "confirmed_visible": ("background:#EAF3DE;border:0.5px solid #3B6D11", "color:#27500A", "color:#3B6D11"),
    "not_confirmed":     ("background:#FAEEDA;border:0.5px solid #854F0B", "color:#633806", "color:#854F0B"),
    "not_visible":       ("background:#F1EFE8;border:0.5px solid #B4B2A9", "color:#5F5E5A", "color:#888780"),
    "needs_review":      ("background:#FCEBEB;border:0.5px solid #A32D2D", "color:#791F1F", "color:#A32D2D"),
}

STAGE_STYLE = {
    1: ("background:#FAECE7;border:1px solid #F0997B", "color:#993C1D", "color:#712B13"),
    2: ("background:#EAF3DE;border:1px solid #97C459", "color:#3B6D11", "color:#27500A"),
    3: ("background:#EEEDFE;border:1px solid #AFA9EC", "color:#534AB7", "color:#3C3489"),
    4: ("background:#E6F1FB;border:1px solid #85B7EB", "color:#185FA5", "color:#0C447C"),
    5: ("background:#FAEEDA;border:1px solid #EF9F27", "color:#854F0B", "color:#633806"),
}


@st.cache_resource
def get_client():
    key_data = json.loads(st.secrets["GCP_SERVICE_ACCOUNT"])
    credentials = service_account.Credentials.from_service_account_info(
        key_data,
        scopes=["https://www.googleapis.com/auth/cloud-platform"]
    )
    return genai.Client(
        vertexai=True,
        project="intellus-build-dev",
        location="us-central1",
        credentials=credentials,
    )


def render_evidence_grid(evidence_pool):
    cols = st.columns(5)
    for idx, (stage_num, info) in enumerate(STAGE_TAXONOMY.items()):
        box_s, num_s, name_s = STAGE_STYLE[stage_num]
        with cols[idx]:
            st.markdown(
                f'<div style="padding:8px 6px;border-radius:8px;text-align:center;'
                f'margin-bottom:8px;{box_s}">'
                f'<div style="font-size:9px;font-weight:500;margin-bottom:2px;{num_s}">Stage {stage_num}</div>'
                f'<div style="font-size:11px;font-weight:500;{name_s}">{info["name"]}</div>'
                f'</div>',
                unsafe_allow_html=True,
            )
            for el in info["elements"]:
                ev     = evidence_pool.get(el, {})
                status = ev.get("status", "not_visible")
                conf   = ev.get("confidence", 0.0)
                flag   = ev.get("flag") or ""
                box_s2, name_s2, meta_s2 = STATUS_STYLE.get(status, STATUS_STYLE["not_visible"])
                conf_str  = f"{int(conf*100)}%" if conf > 0 else ""
                flag_str  = f'<div style="font-size:9px;{meta_s2};opacity:.8;margin-top:2px">{flag.replace("_"," ")}</div>' if flag else ""
                st.markdown(
                    f'<div style="padding:6px 8px;border-radius:8px;margin-bottom:5px;{box_s2}">'
                    f'<div style="font-size:11px;font-weight:500;line-height:1.3;{name_s2}">{el.replace("_"," ")}</div>'
                    f'<div style="font-size:10px;margin-top:2px;{meta_s2}">{conf_str} {status.replace("_"," ")}</div>'
                    f'{flag_str}'
                    f'</div>',
                    unsafe_allow_html=True,
                )


# ── UI ────────────────────────────────────────────────────────────────────────

st.title("Progress Proof")
st.caption("Construction stage detection · Intellus Build · HCAD Harris County")

with st.sidebar:
    st.header("Session settings")
    assessment_date = st.date_input(
        "Assessment date (HCAD anchor)",
        value=date(2026, 1, 1),
        help="Evidence dated after this date is excluded from the appeal analysis.",
    )
    user_date = st.text_input(
        "Photo date override (YYYY-MM-DD)",
        value="",
        help="Applied to photos with no EXIF date. Leave blank to mark as unknown.",
    )
    st.divider()
    st.caption("Upload inspection records or draw schedule to add non-photo evidence.")
    inspection_file = st.file_uploader("Inspection records CSV", type=["csv"])
    draw_file       = st.file_uploader("Draw schedule CSV",      type=["csv"])

uploaded_photos = st.file_uploader(
    "Upload construction site photos",
    type=["jpg", "jpeg", "png", "webp"],
    accept_multiple_files=True,
)

run_button = st.button("Run analysis", type="primary", disabled=not uploaded_photos)

if run_button and uploaded_photos:

    client = get_client()

    image_files = [(f.name, f.read()) for f in uploaded_photos]

    inspection_records = []
    draw_schedule      = []

    if inspection_file:
        import csv, io
        reader = csv.DictReader(io.StringIO(inspection_file.read().decode()))
        for row in reader:
            inspection_records.append({
                "element":   row["element"].strip(),
                "status":    row["status"].strip().lower(),
                "date":      row["date"].strip(),
                "inspector": row.get("inspector", "").strip(),
            })

    if draw_file:
        import csv, io
        reader = csv.DictReader(io.StringIO(draw_file.read().decode()))
        for row in reader:
            draw_schedule.append({
                "stage":    int(row["stage"].strip()),
                "approved": row["approved"].strip().lower() == "yes",
                "date":     row["date"].strip(),
            })

    with st.status("Running analysis...", expanded=True) as status:
        st.write(f"Layer 1 — Processing {len(image_files)} photos...")
        session = run_session(
            image_files=image_files,
            client=client,
            user_date=user_date or None,
        )
        st.write(f"  {session['successful']}/{session['total_photos']} photos processed successfully.")
        if session["failed"]:
            for f in session["failed"]:
                st.write(f"  Failed: {f['filename']} — {f['reason']}")

        st.write("Layer 2 — Aggregating evidence...")
        layer2 = run_aggregation(
            session=session,
            inspection_records=inspection_records,
            draw_schedule=draw_schedule,
            assessment_date=str(assessment_date),
        )

        st.write("Layer 3 — Stage reasoning...")
        layer3 = run_layer3(layer2_output=layer2, client=client)

        status.update(label="Analysis complete", state="complete")

    # handle layer3 error
    if "error" in layer3:
        st.error(f"Layer 3 failed: {layer3['error']}")
        st.stop()

    conclusion = layer3["conclusion"]
    c          = conclusion

    st.divider()

    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Session",          session["session_id"].replace("session_", ""))
    col2.metric("Photos",           session["total_photos"])
    col3.metric("Successful",       session["successful"])
    col4.metric("Stage conclusion", f"{c['stage']} — {c['stage_name']}")
    col5.metric("Confidence",       f"{int(c['confidence']*100)}%")

    if c["needs_human_review"]:
        st.error("Human review required before using this output in a tax appeal.")
        with st.expander("Review reasons", expanded=True):
            for r in c["review_reasons"]:
                st.markdown(f"· {r}")
    else:
        st.success("No human review required. Conclusion is ready for appeal package.")

    st.subheader("Stage reasoning")
    st.write(c["reasoning"])

    if layer3.get("synthesizer_2"):
        with st.expander("Challenger / synthesizer round trip"):
            st.caption("Challenger objections:")
            for obj in c.get("objections", []):
                st.markdown(f"· {obj}")
            st.divider()
            st.caption("Synthesizer response:")
            st.write(layer3["synthesizer_2"].get("reasoning", ""))
    elif c.get("objections"):
        with st.expander("Challenger objections"):
            for obj in c["objections"]:
                st.caption(f"· {obj}")

    if c["blocking_next_stage"]:
        st.caption(f"Blocking next stage: {', '.join(c['blocking_next_stage'])}")

    st.divider()
    st.subheader("Evidence pool")
    render_evidence_grid(layer2["evidence_pool"])

    st.divider()
    col_a, col_b = st.columns(2)

    with col_a:
        st.download_button(
            "Download Layer 2 JSON",
            data=json.dumps(layer2, indent=2),
            file_name=f"{session['session_id']}_layer2.json",
            mime="application/json",
        )
    with col_b:
        st.download_button(
            "Download Layer 3 JSON",
            data=json.dumps(layer3, indent=2),
            file_name=f"{session['session_id']}_layer3.json",
            mime="application/json",
        )