# -*- coding: utf-8 -*-
"""layer1_perception.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HoOCbtF11l-C8FWYcK50nvzGRCDzLbSs
"""

import os
import json
import re
import base64
import piexif
from datetime import datetime
from pathlib import Path
from google import genai
from google.genai import types

from taxonomy import STAGE_TAXONOMY, ALL_ELEMENTS, ELEMENT_KEYS

MODEL_ID = "gemini-2.5-flash"


def build_prompt():
    element_lines = []
    for stage_num, info in STAGE_TAXONOMY.items():
        element_lines.append(f"\nStage {stage_num} — {info['name']}:")
        for el, desc in info["elements"].items():
            element_lines.append(f"  - {el}: {desc}")
    element_list = "\n".join(element_lines)

    schema_lines = []
    for el in ELEMENT_KEYS:
        schema_lines.append(
            f'    "{el}": {{"status": "<confirmed_visible|not_confirmed|not_visible>", '
            f'"confidence": <0.0-1.0>, "evidence": "<what you see>"}}'
        )
    schema = ",\n".join(schema_lines)

    return (
        "You are a licensed construction inspector reviewing a residential property photo "
        "for a Harris County, Texas property tax appeal. Your findings will be used in a "
        "legal document. Accuracy is critical — errors have legal consequences.\n\n"
        "Your job is to inspect this single photograph and report the status of each "
        "construction sub-element listed below. Do NOT classify the overall stage. "
        "Report only what you can directly observe in this photo.\n\n"
        f"Sub-elements to inspect:\n{element_list}\n\n"
        "For each sub-element report exactly one of three statuses:\n"
        '"confirmed_visible" — the element is clearly visible and appears fully complete\n'
        '"not_confirmed" — the element is visible but clearly incomplete or only partially done\n'
        '"not_visible" — the element cannot be assessed from this photo angle\n\n'
        "Critical rules:\n"
        "- Only report what you can directly see. Never infer what might exist off-frame.\n"
        "- not_visible is not a failure — use it whenever you genuinely cannot assess.\n"
        "- Be especially conservative on slab_poured and frame_standing.\n"
        "- confirmed_visible requires clear, unambiguous visual evidence.\n\n"
        "Respond ONLY with a valid JSON object. No markdown, no explanation:\n"
        "{\n"
        '  "photo_description": "<one sentence>",\n'
        '  "detected_elements": {\n'
        f"{schema}\n"
        "  }\n"
        "}"
    )


DETECTION_PROMPT = build_prompt()


def get_photo_date(image_path: str) -> str | None:
    try:
        exif_data = piexif.load(image_path)
        date_raw  = exif_data["Exif"].get(piexif.ExifIFD.DateTimeOriginal)
        if date_raw:
            date_str = date_raw.decode("utf-8")
            return datetime.strptime(date_str, "%Y:%m:%d %H:%M:%S").strftime("%Y-%m-%d")
    except Exception:
        pass
    return None


def get_mime_type(image_path: str) -> str:
    return {
        ".jpg":  "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png":  "image/png",
        ".webp": "image/webp",
    }.get(Path(image_path).suffix.lower(), "image/jpeg")


def parse_response(raw_text: str) -> dict:
    try:
        clean = re.sub(r"```(?:json)?", "", raw_text).strip().rstrip("`").strip()
        match = re.search(r"\{.*\}", clean, re.DOTALL)
        if not match:
            raise ValueError("No JSON object found.")
        parsed   = json.loads(match.group())
        elements = parsed.get("detected_elements", {})
        if not elements:
            raise ValueError("detected_elements missing.")
        for key in ELEMENT_KEYS:
            if key not in elements:
                elements[key] = {"status": "not_visible", "confidence": 0.0, "evidence": "not reported"}
        valid_statuses = {"confirmed_visible", "not_confirmed", "not_visible"}
        for key, val in elements.items():
            if val.get("status") not in valid_statuses:
                val["status"]     = "not_visible"
                val["confidence"] = 0.0
        return {"photo_description": parsed.get("photo_description"), "detected_elements": elements, "parse_error": None}
    except Exception as e:
        return {
            "photo_description": None,
            "detected_elements": {
                key: {"status": "not_visible", "confidence": 0.0, "evidence": "parse_error"}
                for key in ELEMENT_KEYS
            },
            "parse_error": str(e),
        }


def run_perception(image_bytes: bytes, filename: str, client, user_date: str = None) -> dict:
    photo_date, photo_date_source = None, "unknown"

    import tempfile, os
    with tempfile.NamedTemporaryFile(delete=False, suffix=Path(filename).suffix) as tmp:
        tmp.write(image_bytes)
        tmp_path = tmp.name

    exif_date = get_photo_date(tmp_path)
    os.unlink(tmp_path)

    if exif_date:
        photo_date, photo_date_source = exif_date, "exif"
    elif user_date:
        photo_date, photo_date_source = user_date, "user"

    mime_type = get_mime_type(filename)

    try:
        response  = client.models.generate_content(
            model=MODEL_ID,
            contents=[
                types.Part.from_bytes(data=image_bytes, mime_type=mime_type),
                DETECTION_PROMPT,
            ],
        )
        parsed    = parse_response(response.text)
        raw_error = None
    except Exception as e:
        parsed    = parse_response("")
        raw_error = f"API error: {str(e)}"

    return {
        "filename":          filename,
        "photo_date":        photo_date,
        "photo_date_source": photo_date_source,
        "photo_description": parsed["photo_description"],
        "detected_elements": parsed["detected_elements"],
        "parse_error":       parsed["parse_error"],
        "raw_error":         raw_error,
    }


def run_session(image_files: list[tuple], client, session_id: str = None, user_date: str = None) -> dict:
    """
    image_files: list of (filename, bytes) tuples
    """
    if not session_id:
        session_id = f"session_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    photo_results = []
    failed        = []

    for filename, image_bytes in image_files:
        result = run_perception(image_bytes, filename, client, user_date=user_date)
        photo_results.append(result)
        if result["raw_error"] or result["parse_error"]:
            failed.append({
                "filename": filename,
                "reason":   result["raw_error"] or result["parse_error"],
            })

    return {
        "session_id":    session_id,
        "total_photos":  len(photo_results),
        "successful":    len(photo_results) - len(failed),
        "failed":        failed,
        "photo_results": photo_results,
    }