# -*- coding: utf-8 -*-
"""layer3_reasoner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pTaEwrN3RpqoLVY3M2U5j8o3R42B_qd
"""

import json
import re
from taxonomy import STAGE_TAXONOMY, ALL_ELEMENTS, ELEMENT_KEYS, CRITICAL_ELEMENTS

MODEL_ID               = "gemini-2.5-flash"
AUTO_CONFIRM_THRESHOLD = 0.80


def run_binary_gate(evidence_pool):
    confirmed_stages   = []
    blocking_per_stage = {}

    for stage_num, info in STAGE_TAXONOMY.items():
        blocking        = []
        needs_rev_block = []
        gap_block       = []

        for el in info["elements"]:
            ev     = evidence_pool.get(el, {})
            status = ev.get("status")
            flag   = ev.get("flag")
            if status == "confirmed_visible":
                continue
            blocking.append(el)
            if status == "needs_review":
                needs_rev_block.append(el)
            if flag == "coverage_gap":
                gap_block.append(el)

        blocking_per_stage[stage_num] = {
            "blocking":      blocking,
            "needs_review":  needs_rev_block,
            "coverage_gaps": gap_block,
        }
        if not blocking:
            confirmed_stages.append(stage_num)

    return {
        "candidate_stage":    max(confirmed_stages) if confirmed_stages else 0,
        "confirmed_stages":   confirmed_stages,
        "blocking_per_stage": blocking_per_stage,
    }


def _call_gemini(prompt, client):
    response = client.models.generate_content(model=MODEL_ID, contents=[prompt])
    raw      = response.text
    clean    = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()
    match    = re.search(r"\{.*\}", clean, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON in response. Raw: {raw[:300]}")
    return json.loads(match.group())


def run_synthesizer(evidence_pool, gate_result, assessment_date, client):
    candidate = gate_result["candidate_stage"]

    evidence_lines = []
    for stage_num, info in STAGE_TAXONOMY.items():
        evidence_lines.append(f"\nStage {stage_num} — {info['name']}:")
        for el in info["elements"]:
            ev   = evidence_pool.get(el, {})
            line = f"  {el}: {ev.get('status','unknown')} (confidence: {ev.get('confidence',0.0)})"
            if ev.get("flag"):
                line += f" [FLAG: {ev['flag']}]"
            evidence_lines.append(line)

    blocking_text = ""
    for sn, b in gate_result["blocking_per_stage"].items():
        if b["blocking"]:
            blocking_text += f"\n  Stage {sn}: blocked by {b['blocking']}"

    high_conf = []
    for el, ev in evidence_pool.items():
        if ev.get("status") == "confirmed_visible" and ev.get("confidence", 0) >= 0.85:
            sn = next((item["stage"] for item in ALL_ELEMENTS if item["element"] == el), None)
            high_conf.append(f"{el} (stage {sn}, confidence {ev['confidence']})")

    prompt = f"""You are a senior construction inspector and property tax expert reviewing a Harris County, Texas residential property for a tax appeal under HCAD guidelines.

You are the SYNTHESIZER. Propose the most accurate and honest construction stage conclusion.

ASSESSMENT DATE: {assessment_date}

BINARY GATE RESULT:
Highest fully confirmed stage: Stage {candidate}
Note: binary gate is a strict completeness check. Propose the best-supported stage given all evidence.
Blocking per stage:{blocking_text if blocking_text else " none"}

HIGH-CONFIDENCE CONFIRMED ELEMENTS (confidence >= 0.85):
{chr(10).join(f'  - {e}' for e in high_conf) if high_conf else '  none'}

FULL EVIDENCE POOL:
{chr(10).join(evidence_lines)}

HCAD STAGE DEFINITIONS:
Stage 0 — No confirmed stage: zero evidence of any construction
Stage 1 — Raw Land: undeveloped, no utilities, no improvements
Stage 2 — Developed Land: site work, utilities, drainage, parking, fencing
Stage 3 — Dried-In Building: slab, frame, roof, windows, doors, cladding
Stage 4 — Pre-Sheetrock: all rough-ins, insulation
Stage 5 — Finished Building: all finishes, flooring, paint, fixtures, appliances

CRITICAL RULES:
- Stage 0 means ZERO confirmed elements. Never propose Stage 0 if any element is confirmed_visible.
- If frame_standing or any Stage 3+ element is confirmed, property is at minimum Stage 2.
- Binary gate result of 0 means no stage is fully complete — not that property is Stage 0.
- Be conservative but honest. Propose the highest stage that is clearly supported.
- needs_review elements cannot be treated as confirmed.

Respond ONLY with valid JSON, no markdown:
{{
  "proposed_stage": <integer 0-5>,
  "confidence": <0.0-1.0>,
  "reasoning": "<2-3 sentences>",
  "key_confirmed_elements": ["<element>", ...],
  "key_blocking_elements": ["<element>", ...]
}}"""

    return _call_gemini(prompt, client)


def run_challenger(evidence_pool, synthesizer_result, assessment_date, client):
    proposed   = synthesizer_result.get("proposed_stage", 0)
    reasoning  = synthesizer_result.get("reasoning", "")
    confirmed  = synthesizer_result.get("key_confirmed_elements", [])
    blocking   = synthesizer_result.get("key_blocking_elements", [])

    confirmed_text = ""
    for el in confirmed:
        ev = evidence_pool.get(el, {})
        confirmed_text += (
            f"\n  {el}: {ev.get('status')} (confidence: {ev.get('confidence')})"
            + (f" [FLAG: {ev.get('flag')}]" if ev.get("flag") else "")
            + (f" — seen in: {', '.join(ev.get('supporting_photos', []))}" if ev.get("supporting_photos") else "")
        )

    blocking_text = ""
    for el in blocking:
        ev = evidence_pool.get(el, {})
        blocking_text += f"\n  {el}: {ev.get('status')}" + (f" [{ev.get('flag')}]" if ev.get("flag") else "")

    prompt = f"""You are a senior construction inspector and property tax expert reviewing a Harris County, Texas residential property for a tax appeal under HCAD guidelines.

You are the CHALLENGER. Determine whether the synthesizer's conclusion is too high, too low, or correct.

ASSESSMENT DATE: {assessment_date}

SYNTHESIZER CONCLUSION:
Proposed stage: {proposed}
Reasoning: {reasoning}

KEY CONFIRMED ELEMENTS:
{confirmed_text if confirmed_text else "  none"}

KEY BLOCKING ELEMENTS:
{blocking_text if blocking_text else "  none"}

CHECK BOTH DIRECTIONS:

TOO HIGH?
- Could confirmed elements belong to a neighboring building?
- Is photo coverage sufficient for the entire property?

TOO LOW?
- Are high-confidence higher-stage elements being ignored?
- If frame_standing confirmed at high confidence, property is at minimum in Stage 3 work.
- If synthesizer proposed Stage 0 but elements are confirmed — that is a logic error.

CORRECT?
- If conclusion accurately reflects evidence, confirm it.

Respond ONLY with valid JSON, no markdown:
{{
  "objections": ["<specific objection>", ...],
  "overrides_conclusion": <true/false>,
  "recommended_stage": <integer 0-5>,
  "direction": "<higher/lower/correct>",
  "override_reasoning": "<why stage should change, or No override — conclusion is sound>"
}}"""

    return _call_gemini(prompt, client)


def resolve_conclusion(synthesizer_result, challenger_result, gate_result, evidence_pool):
    proposed   = synthesizer_result.get("proposed_stage", 0)
    synth_conf = synthesizer_result.get("confidence", 0.0)
    synth_reas = synthesizer_result.get("reasoning", "")
    overrides  = challenger_result.get("overrides_conclusion", False)
    objections = challenger_result.get("objections", [])
    rec_stage  = challenger_result.get("recommended_stage", proposed)
    direction  = challenger_result.get("direction", "correct")
    override_r = challenger_result.get("override_reasoning", "")

    if overrides and rec_stage is not None and rec_stage != proposed:
        final_stage = rec_stage
        final_conf  = max(synth_conf - (0.10 if rec_stage > proposed else 0.15), 0.0)
        final_reas  = f"{synth_reas} CHALLENGER {'UPGRADE' if rec_stage > proposed else 'OVERRIDE'}: {override_r}"
        was_challenged = True
    else:
        final_stage    = proposed
        final_conf     = synth_conf
        final_reas     = synth_reas
        was_challenged = False

    next_stage    = final_stage + 1
    next_blocking = gate_result["blocking_per_stage"].get(
        next_stage,
        gate_result["blocking_per_stage"].get(str(next_stage), {})
    )
    stage_name = STAGE_TAXONOMY.get(final_stage, {}).get("name", "Unknown")

    return {
        "stage":               final_stage,
        "stage_name":          stage_name,
        "confidence":          round(final_conf, 3),
        "reasoning":           final_reas,
        "was_challenged":      was_challenged,
        "direction":           direction,
        "objections":          objections,
        "blocking_next_stage": next_blocking.get("blocking", []),
        "coverage_gaps":       next_blocking.get("coverage_gaps", []),
    }


def apply_human_review_gate(conclusion, gate_result, evidence_pool):
    review_reasons = []

    if conclusion["confidence"] < AUTO_CONFIRM_THRESHOLD:
        review_reasons.append(f"Confidence {conclusion['confidence']} below threshold {AUTO_CONFIRM_THRESHOLD}")

    if conclusion["was_challenged"]:
        review_reasons.append("Challenger agent overrode the synthesizer conclusion")

    if gate_result["candidate_stage"] == 0:
        review_reasons.append("Binary gate found no fully confirmed stage from photo evidence")

    for el in CRITICAL_ELEMENTS:
        ev = evidence_pool.get(el, {})
        if ev.get("status") == "needs_review":
            review_reasons.append(f"Critical element '{el}' is flagged needs_review")
        if ev.get("flag") == "coverage_gap":
            review_reasons.append(f"Critical element '{el}' has a coverage gap — insufficient photos")

    conclusion["needs_human_review"] = len(review_reasons) > 0
    conclusion["review_reasons"]     = review_reasons
    return conclusion


def run_layer3(layer2_output, client):
    evidence_pool = layer2_output["evidence_pool"]
    assessment_date = layer2_output["assessment_date"]

    gate_result        = run_binary_gate(evidence_pool)
    synthesizer_result = run_synthesizer(evidence_pool, gate_result, assessment_date, client)
    challenger_result  = run_challenger(evidence_pool, synthesizer_result, assessment_date, client)
    conclusion         = resolve_conclusion(synthesizer_result, challenger_result, gate_result, evidence_pool)
    conclusion         = apply_human_review_gate(conclusion, gate_result, evidence_pool)

    return {
        "session_id":      layer2_output["session_id"],
        "assessment_date": assessment_date,
        "total_photos":    layer2_output["total_photos"],
        "binary_gate":     gate_result,
        "synthesizer":     synthesizer_result,
        "challenger":      challenger_result,
        "conclusion":      conclusion,
    }