# -*- coding: utf-8 -*-
"""layer2_aggregation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZA588j9-FHyEbjIOmyAJnriyKrOaERYo
"""

from taxonomy import STAGE_TAXONOMY, ALL_ELEMENTS, ELEMENT_KEYS

HIGH_CONF_THRESHOLD  = 0.85
LOW_CONF_THRESHOLD   = 0.60
CONFIRMED_THRESHOLD  = 0.80
COVERAGE_GAP_RATIO   = 0.80

FLAG_NONE            = None
FLAG_COVERAGE_GAP    = "coverage_gap"
FLAG_DISAGREEMENT    = "model_disagreement"
FLAG_TEMPORAL        = "temporal_inconsistency"
FLAG_LOW_CONFIDENCE  = "low_confidence"
FLAG_SOURCE_CONFLICT = "source_conflict"


def passes_date_filter(photo_date, assessment_date):
    if not photo_date:
        return True
    return photo_date <= assessment_date


def check_inspection_override(element_key, inspection_records, assessment_date):
    applicable = [
        r for r in inspection_records
        if r["element"] == element_key and r["date"] <= assessment_date
    ]
    if not applicable:
        return None
    record = sorted(applicable, key=lambda x: x["date"], reverse=True)[0]
    return {
        "status":             "confirmed_visible" if record["status"] == "pass" else "not_confirmed",
        "confidence":         0.95,
        "source":             "inspection_record",
        "supporting_photos":  [],
        "conflicting_photos": [],
        "flag":               FLAG_NONE,
        "notes":              f"Inspection record {record['date']} — {record.get('inspector','')}",
    }


def check_temporal_consistency(dated_detections):
    sorted_d = sorted(dated_detections, key=lambda x: x["date"])
    for i in range(1, len(sorted_d)):
        prev, curr = sorted_d[i-1], sorted_d[i]
        if (prev["status"] == "confirmed_visible"
                and curr["status"] == "not_confirmed"
                and prev["confidence"] >= HIGH_CONF_THRESHOLD
                and curr["confidence"] >= HIGH_CONF_THRESHOLD):
            return True
    return False


def aggregate_element_photos(element_key, photo_results, assessment_date):
    all_detections = []
    for photo in photo_results:
        el = photo["detected_elements"].get(element_key)
        if not el:
            continue
        all_detections.append({
            "filename":   photo["filename"],
            "status":     el["status"],
            "confidence": el["confidence"],
            "evidence":   el["evidence"],
            "date":       photo.get("photo_date"),
        })

    filtered      = [d for d in all_detections if passes_date_filter(d["date"], assessment_date)]
    excluded_count = len(all_detections) - len(filtered)

    if not filtered:
        return {"status": "not_visible", "confidence": 0.0, "source": "photos",
                "supporting_photos": [], "conflicting_photos": [],
                "flag": FLAG_COVERAGE_GAP, "notes": f"All {excluded_count} photo(s) post-date assessment."}

    not_visible_count = sum(1 for d in filtered if d["status"] == "not_visible")
    if not_visible_count / len(filtered) >= COVERAGE_GAP_RATIO:
        return {"status": "not_visible", "confidence": 0.0, "source": "photos",
                "supporting_photos": [], "conflicting_photos": [],
                "flag": FLAG_COVERAGE_GAP, "notes": f"{not_visible_count}/{len(filtered)} photos cannot see this element."}

    visible = [d for d in filtered if d["status"] != "not_visible" and d["confidence"] >= LOW_CONF_THRESHOLD]

    if not visible:
        return {"status": "not_visible", "confidence": 0.0, "source": "photos",
                "supporting_photos": [], "conflicting_photos": [],
                "flag": FLAG_COVERAGE_GAP, "notes": "No detections cleared confidence threshold."}

    dated_visible  = [d for d in visible if d["date"]]
    temporal_flag  = FLAG_TEMPORAL if len(dated_visible) >= 2 and check_temporal_consistency(dated_visible) else FLAG_NONE

    confirmed_group    = [d for d in visible if d["status"] == "confirmed_visible"]
    not_conf_group     = [d for d in visible if d["status"] == "not_confirmed"]
    high_conf_confirmed = [d for d in confirmed_group if d["confidence"] >= HIGH_CONF_THRESHOLD]
    high_conf_not_conf  = [d for d in not_conf_group  if d["confidence"] >= HIGH_CONF_THRESHOLD]

    if high_conf_confirmed and high_conf_not_conf:
        return {"status": "needs_review", "confidence": 0.0, "source": "photos",
                "supporting_photos":  [d["filename"] for d in high_conf_confirmed],
                "conflicting_photos": [d["filename"] for d in high_conf_not_conf],
                "flag": FLAG_DISAGREEMENT,
                "notes": f"{len(high_conf_confirmed)} photo(s) confirm, {len(high_conf_not_conf)} deny."}

    if confirmed_group:
        weighted_conf = sum(d["confidence"] for d in confirmed_group) / len(confirmed_group)
        has_strong    = bool(high_conf_confirmed)
        no_denial     = not high_conf_not_conf

        if has_strong and no_denial and weighted_conf >= CONFIRMED_THRESHOLD:
            flag  = temporal_flag or FLAG_NONE
            notes = ""
            if weighted_conf < HIGH_CONF_THRESHOLD:
                flag  = FLAG_LOW_CONFIDENCE
                notes = "Confirmed but borderline confidence."
            unknown = sum(1 for d in visible if not d["date"])
            if unknown:
                notes += f" {unknown} photo(s) have no date metadata."
            return {"status": "confirmed_visible", "confidence": round(weighted_conf, 3),
                    "source": "photos",
                    "supporting_photos":  [d["filename"] for d in confirmed_group],
                    "conflicting_photos": [d["filename"] for d in not_conf_group],
                    "flag": flag, "notes": notes.strip()}

    weighted_conf = sum(d["confidence"] for d in not_conf_group) / len(not_conf_group) if not_conf_group else 0.0
    return {"status": "not_confirmed", "confidence": round(weighted_conf, 3),
            "source": "photos",
            "supporting_photos":  [d["filename"] for d in not_conf_group],
            "conflicting_photos": [d["filename"] for d in confirmed_group],
            "flag": temporal_flag, "notes": ""}


def run_aggregation(session, inspection_records, draw_schedule, assessment_date):
    photo_results = session["photo_results"]
    evidence_pool = {}
    needs_review  = []
    coverage_gaps = []

    for item in ALL_ELEMENTS:
        el = item["element"]

        override = check_inspection_override(el, inspection_records, assessment_date)
        if override:
            evidence_pool[el] = override
            continue

        photo_ev = aggregate_element_photos(el, photo_results, assessment_date)

        if inspection_records:
            insp_ev = check_inspection_override(el, inspection_records, assessment_date)
            if (insp_ev
                    and photo_ev["status"] == "confirmed_visible"
                    and insp_ev["status"] == "not_confirmed"):
                photo_ev["flag"]  = FLAG_SOURCE_CONFLICT
                photo_ev["notes"] = "Photos confirm but inspection record says fail."

        evidence_pool[el] = photo_ev

        if photo_ev["flag"] == FLAG_DISAGREEMENT:
            needs_review.append(el)
        if photo_ev["flag"] == FLAG_COVERAGE_GAP:
            coverage_gaps.append(el)

    confirmed   = [el for el, ev in evidence_pool.items() if ev["status"] == "confirmed_visible"]
    not_conf    = [el for el, ev in evidence_pool.items() if ev["status"] == "not_confirmed"]
    not_visible = [el for el, ev in evidence_pool.items() if ev["status"] == "not_visible"]
    review      = [el for el, ev in evidence_pool.items() if ev["status"] == "needs_review"]

    return {
        "session_id":      session["session_id"],
        "assessment_date": assessment_date,
        "total_photos":    session["total_photos"],
        "summary": {
            "confirmed_count":  len(confirmed),
            "not_confirmed":    len(not_conf),
            "not_visible":      len(not_visible),
            "needs_review":     len(review),
            "coverage_gaps":    coverage_gaps,
            "flagged_elements": needs_review,
        },
        "evidence_pool": evidence_pool,
    }