# -*- coding: utf-8 -*-
"""layer3_reasoner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pTaEwrN3RpqoLVY3M2U5j8o3R42B_qd
"""

import json
import re
from taxonomy import STAGE_TAXONOMY, ALL_ELEMENTS, ELEMENT_KEYS

MODEL_ID               = "gemini-2.5-flash"
AUTO_CONFIRM_THRESHOLD = 0.80


def run_binary_gate(evidence_pool):
    confirmed_stages   = []
    blocking_per_stage = {}

    for stage_num, info in STAGE_TAXONOMY.items():
        blocking        = []
        needs_rev_block = []
        gap_block       = []

        for el in info["elements"]:
            ev     = evidence_pool.get(el, {})
            status = ev.get("status")
            flag   = ev.get("flag")
            if status == "confirmed_visible":
                continue
            blocking.append(el)
            if status == "needs_review":
                needs_rev_block.append(el)
            if flag == "coverage_gap":
                gap_block.append(el)

        blocking_per_stage[stage_num] = {
            "blocking":      blocking,
            "needs_review":  needs_rev_block,
            "coverage_gaps": gap_block,
        }
        if not blocking:
            confirmed_stages.append(stage_num)

    return {
        "candidate_stage":    max(confirmed_stages) if confirmed_stages else 0,
        "confirmed_stages":   confirmed_stages,
        "blocking_per_stage": blocking_per_stage,
    }


def _call_gemini(prompt, client):
    try:
        response = client.models.generate_content(model=MODEL_ID, contents=[prompt])
        raw      = response.text
        clean    = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()
        match    = re.search(r"\{.*\}", clean, re.DOTALL)
        if not match:
            raise ValueError(f"No JSON in response. Raw: {raw[:300]}")
        return json.loads(match.group()), None
    except Exception as e:
        return None, str(e)


def run_synthesizer(evidence_pool, gate_result, assessment_date, client, challenger_objections=None, challenger_recommended_stage=None):
    candidate = gate_result["candidate_stage"]

    evidence_lines = []
    for stage_num, info in STAGE_TAXONOMY.items():
        evidence_lines.append(f"\nStage {stage_num} — {info['name']}:")
        for el in info["elements"]:
            ev   = evidence_pool.get(el, {})
            line = f"  {el}: {ev.get('status','unknown')} (confidence: {ev.get('confidence',0.0)})"
            if ev.get("flag"):
                line += f" [FLAG: {ev['flag']}]"
            evidence_lines.append(line)

    blocking_text = ""
    for sn, b in gate_result["blocking_per_stage"].items():
        if b["blocking"]:
            blocking_text += f"\n  Stage {sn}: blocked by {b['blocking']}"

    challenger_section = ""
    if challenger_objections:
        challenger_section = f"""
CHALLENGER OBJECTIONS YOU MUST RESPOND TO:
{chr(10).join(f'  - {obj}' for obj in challenger_objections)}

CHALLENGER RECOMMENDED STAGE: {challenger_recommended_stage}

You must address each objection specifically in your reasoning. If you still believe your original conclusion is correct, explain why each objection is wrong. If the challenger has identified a valid error, correct it.
"""

    prompt = f"""You are a senior construction inspector and property tax expert reviewing a Harris County, Texas residential property for a tax appeal under HCAD guidelines.

You are the SYNTHESIZER.{'This is your second review — the challenger has objected to your first conclusion.' if challenger_objections else ''}

ASSESSMENT DATE: {assessment_date}

HCAD STAGE DEFINITIONS:
Stage 1 — Raw Land: undeveloped, no utilities, no improvements
Stage 2 — Developed Land: site work, utilities, drainage, parking, fencing
Stage 3 — Dried-In Building: slab, frame, roof, windows, doors, cladding
Stage 4 — Pre-Sheetrock: all rough-ins, insulation
Stage 5 — Finished Building: all finishes, flooring, paint, fixtures, appliances

BINARY GATE RESULT:
Highest fully confirmed stage (all elements explicitly confirmed): Stage {candidate}
Blocking per stage:{blocking_text if blocking_text else " none"}

FULL EVIDENCE POOL:
{chr(10).join(evidence_lines)}
{challenger_section}
CORE RULES:
1. The binary gate result is your starting point. A stage is only confirmed when ALL its sub-elements are complete.
2. The final conclusion must be rounded down to the last fully gated stage unless downward inference applies (see rule 3).
3. DOWNWARD INFERENCE ONLY: if a high-confidence element is confirmed, you may infer that lower-stage elements with coverage gaps are complete — because construction is sequential and you cannot reach a later stage without completing earlier ones.
4. needs_review and coverage_gap elements cannot be treated as confirmed unless downward inference from a higher confirmed element justifies it.
5. Be conservative. When in doubt, round down.

Respond ONLY with valid JSON, no markdown:
{{
  "proposed_stage": <integer 0-5>,
  "confidence": <0.0-1.0>,
  "reasoning": "<2-3 sentences explaining the conclusion, any inference applied, and if this is a second review — your response to each challenger objection>",
  "key_confirmed_elements": ["<element>", ...],
  "key_blocking_elements": ["<element>", ...],
  "inferred_elements": ["<element>", ...]
}}"""

    return _call_gemini(prompt, client)


def run_challenger(evidence_pool, synthesizer_result, assessment_date, client):
    proposed      = synthesizer_result.get("proposed_stage", 0)
    reasoning     = synthesizer_result.get("reasoning", "")
    confirmed     = synthesizer_result.get("key_confirmed_elements", [])
    blocking      = synthesizer_result.get("key_blocking_elements", [])
    inferred      = synthesizer_result.get("inferred_elements", [])

    confirmed_text = ""
    for el in confirmed:
        ev = evidence_pool.get(el, {})
        confirmed_text += (
            f"\n  {el}: {ev.get('status')} (confidence: {ev.get('confidence')})"
            + (f" [FLAG: {ev.get('flag')}]" if ev.get("flag") else "")
            + (f" — seen in: {', '.join(ev.get('supporting_photos', []))}" if ev.get("supporting_photos") else "")
        )

    blocking_text = ""
    for el in blocking:
        ev = evidence_pool.get(el, {})
        blocking_text += f"\n  {el}: {ev.get('status')}" + (f" [{ev.get('flag')}]" if ev.get("flag") else "")

    inferred_text = ""
    for el in inferred:
        ev = evidence_pool.get(el, {})
        inferred_text += f"\n  {el}: {ev.get('status')} (confidence: {ev.get('confidence')})" + (f" [FLAG: {ev.get('flag')}]" if ev.get("flag") else "")

    prompt = f"""You are a senior construction inspector and property tax expert reviewing a Harris County, Texas residential property for a tax appeal under HCAD guidelines.

You are the CHALLENGER. Your job is to verify whether the synthesizer's conclusion is correct, too high, or too low.

ASSESSMENT DATE: {assessment_date}

SYNTHESIZER CONCLUSION:
Proposed stage: {proposed}
Reasoning: {reasoning}

KEY CONFIRMED ELEMENTS:
{confirmed_text if confirmed_text else "  none"}

KEY BLOCKING ELEMENTS:
{blocking_text if blocking_text else "  none"}

INFERRED ELEMENTS (synthesizer applied downward inference to these):
{inferred_text if inferred_text else "  none"}

CORE RULES YOU MUST ENFORCE:
1. A stage is only confirmed when ALL its sub-elements are explicitly confirmed or justifiably inferred complete via downward inference.
2. Downward inference is only valid from a high-confidence confirmed element to lower-stage coverage gaps. Never upward.
3. If the synthesizer inferred elements upward or without sufficient confidence basis, that is an error.
4. If the synthesizer ignored high-confidence confirmed elements that justify downward inference, that is an error.
5. The conclusion must always round down when evidence is insufficient. Conservative is correct.

CHECK BOTH DIRECTIONS:
TOO HIGH?
- Did the synthesizer infer upward? That is not allowed.
- Are blocking elements genuinely unresolved with no valid downward inference basis?
- Could confirmed elements belong to a neighboring property?

TOO LOW?
- Did the synthesizer ignore valid downward inference from high-confidence confirmed elements?
- Are coverage gap elements at lower stages clearly implied by high-confidence higher-stage confirmations?

CORRECT?
- If the conclusion accurately reflects the binary gate result and any valid downward inference, confirm it.

Respond ONLY with valid JSON, no markdown:
{{
  "objections": ["<specific objection>", ...],
  "overrides_conclusion": <true/false>,
  "recommended_stage": <integer 0-5>,
  "direction": "<higher/lower/correct>",
  "override_reasoning": "<why stage should change, or No override — conclusion is sound>"
}}"""

    return _call_gemini(prompt, client)


def resolve_conclusion(synthesizer_result, synthesizer_result_2, challenger_result, gate_result, evidence_pool):
    overrides  = challenger_result.get("overrides_conclusion", False)
    objections = challenger_result.get("objections", [])
    direction  = challenger_result.get("direction", "correct")

    if not overrides:
        # challenger agreed with first synthesizer
        final_result   = synthesizer_result
        was_challenged = False
        human_review_reason = None
    else:
        if synthesizer_result_2 is None:
            # second synthesizer call failed, take challenger's recommended stage conservatively
            final_result   = synthesizer_result
            was_challenged = True
            human_review_reason = "Second synthesizer call failed after challenger override"
        else:
            s1_stage = synthesizer_result.get("proposed_stage", 0)
            s2_stage = synthesizer_result_2.get("proposed_stage", 0)
            c_stage  = challenger_result.get("recommended_stage", s1_stage)

            if s2_stage == c_stage:
                # synthesizer accepted challenger's correction
                final_result        = synthesizer_result_2
                was_challenged      = True
                human_review_reason = None
            else:
                # still disagreeing — take lower stage and flag for human review
                if s2_stage < c_stage:
                    final_result = synthesizer_result_2
                else:
                    final_result = {
                        "proposed_stage":        c_stage,
                        "confidence":            max(synthesizer_result_2.get("confidence", 0.0) - 0.15, 0.0),
                        "reasoning":             synthesizer_result_2.get("reasoning", ""),
                        "key_confirmed_elements": synthesizer_result_2.get("key_confirmed_elements", []),
                        "key_blocking_elements":  synthesizer_result_2.get("key_blocking_elements", []),
                        "inferred_elements":      synthesizer_result_2.get("inferred_elements", []),
                    }
                was_challenged      = True
                human_review_reason = "Synthesizer and challenger could not agree after full round trip"

    final_stage = final_result.get("proposed_stage", 0)
    final_conf  = final_result.get("confidence", 0.0)
    final_reas  = final_result.get("reasoning", "")
    stage_name  = STAGE_TAXONOMY.get(final_stage, {}).get("name", "Unknown")

    next_stage    = final_stage + 1
    next_blocking = gate_result["blocking_per_stage"].get(
        next_stage,
        gate_result["blocking_per_stage"].get(str(next_stage), {})
    )

    return {
        "stage":               final_stage,
        "stage_name":          stage_name,
        "confidence":          round(final_conf, 3),
        "reasoning":           final_reas,
        "was_challenged":      was_challenged,
        "direction":           direction,
        "objections":          objections,
        "blocking_next_stage": next_blocking.get("blocking", []),
        "coverage_gaps":       next_blocking.get("coverage_gaps", []),
        "_human_review_reason_from_resolver": human_review_reason,
    }


def apply_human_review_gate(conclusion, gate_result, evidence_pool):
    review_reasons = []

    if conclusion["confidence"] < AUTO_CONFIRM_THRESHOLD:
        review_reasons.append(f"Confidence {conclusion['confidence']} below threshold {AUTO_CONFIRM_THRESHOLD}")

    if conclusion["was_challenged"]:
        review_reasons.append("Challenger agent overrode the synthesizer conclusion")

    if conclusion.get("_human_review_reason_from_resolver"):
        review_reasons.append(conclusion["_human_review_reason_from_resolver"])

    if gate_result["candidate_stage"] == 0:
        review_reasons.append("Binary gate found no fully confirmed stage from photo evidence")

    for el, ev in evidence_pool.items():
        if ev.get("status") == "needs_review":
            review_reasons.append(f"Element '{el}' is flagged needs_review")
        if ev.get("flag") == "coverage_gap":
            review_reasons.append(f"Element '{el}' has a coverage gap — insufficient photos")

    conclusion["needs_human_review"] = len(review_reasons) > 0
    conclusion["review_reasons"]     = review_reasons
    conclusion.pop("_human_review_reason_from_resolver", None)
    return conclusion


def run_layer3(layer2_output, client):
    evidence_pool   = layer2_output["evidence_pool"]
    assessment_date = layer2_output["assessment_date"]

    gate_result = run_binary_gate(evidence_pool)

    synthesizer_result, synth_err = run_synthesizer(evidence_pool, gate_result, assessment_date, client)
    if synthesizer_result is None:
        return {
            "session_id":      layer2_output["session_id"],
            "assessment_date": assessment_date,
            "total_photos":    layer2_output["total_photos"],
            "error":           f"Synthesizer failed: {synth_err}",
            "conclusion": {
                "stage": 0, "stage_name": "Unknown", "confidence": 0.0,
                "needs_human_review": True, "review_reasons": [f"Synthesizer failed: {synth_err}"],
            }
        }

    challenger_result, chall_err = run_challenger(evidence_pool, synthesizer_result, assessment_date, client)
    if challenger_result is None:
        return {
            "session_id":      layer2_output["session_id"],
            "assessment_date": assessment_date,
            "total_photos":    layer2_output["total_photos"],
            "error":           f"Challenger failed: {chall_err}",
            "conclusion": {
                "stage": synthesizer_result.get("proposed_stage", 0),
                "stage_name": STAGE_TAXONOMY.get(synthesizer_result.get("proposed_stage", 0), {}).get("name", "Unknown"),
                "confidence": 0.0,
                "needs_human_review": True,
                "review_reasons": [f"Challenger failed: {chall_err}"],
            }
        }

    synthesizer_result_2 = None
    if challenger_result.get("overrides_conclusion"):
        synthesizer_result_2, _ = run_synthesizer(
            evidence_pool, gate_result, assessment_date, client,
            challenger_objections=challenger_result.get("objections", []),
            challenger_recommended_stage=challenger_result.get("recommended_stage"),
        )

    conclusion = resolve_conclusion(synthesizer_result, synthesizer_result_2, challenger_result, gate_result, evidence_pool)
    conclusion = apply_human_review_gate(conclusion, gate_result, evidence_pool)

    return {
        "session_id":        layer2_output["session_id"],
        "assessment_date":   assessment_date,
        "total_photos":      layer2_output["total_photos"],
        "binary_gate":       gate_result,
        "synthesizer_1":     synthesizer_result,
        "challenger":        challenger_result,
        "synthesizer_2":     synthesizer_result_2,
        "conclusion":        conclusion,
    }