# -*- coding: utf-8 -*-
"""Taxonomy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNUc8awrjRlg2jgCbwXKT20FeS1Fq5s0
"""

STAGE_TAXONOMY = {
    1: {
        "name": "Raw Land",
        "elements": {
            "undeveloped_property":  "Land that is completely raw and undeveloped with no site work visible",
            "no_utilities":          "No utility connections visible — no meters, no service lines, no electrical/water/gas hookups at the property",
            "no_improvements":       "No physical improvements visible — no grading, no clearing, no structures of any kind",
        }
    },
    2: {
        "name": "Developed Land",
        "elements": {
            "demolition_clearing_grubbing": "Evidence of demolition, land clearing, or grubbing — removed vegetation, stumps, debris piles, scraped earth",
            "grading":                      "Graded and leveled earth visible — smooth or sloped soil prepared for construction",
            "utilities_installed":          "Utility connections visible at the property — electrical meters, water lines, gas meters, sewer caps, or utility trenches",
            "drainage_systems":             "Drainage infrastructure visible — pipes, culverts, retention areas, or drainage channels",
            "parking_driveways":            "Paved or gravel parking areas or driveways visible",
            "fencing":                      "Perimeter or site fencing installed and visible",
        }
    },
    3: {
        "name": "Dried-In Building",
        "elements": {
            "slab_poured":              "Complete concrete foundation slab fully poured and covering the entire building footprint — NOT driveways or walkways",
            "frame_standing":           "Complete structural wood or steel frame standing for the full building — walls, floors, and roof structure erected",
            "roof_complete":            "Roof fully sheathed and covered with final roofing material — shingles, tile, metal, or membrane",
            "windows_installed":        "Windows installed in all openings — frames and glazing in place",
            "exterior_doors_installed": "Exterior doors installed in all door openings",
            "exterior_cladding":        "Exterior wall cladding applied to all walls — hardie board, brick, stucco, or similar finish material",
        }
    },
    4: {
        "name": "Pre-Sheetrock",
        "elements": {
            "electrical_rough_in": "Electrical wiring and boxes roughed in and visible in open wall cavities before drywall",
            "hvac_installed":      "HVAC ductwork, air handler, or mechanical equipment visible and installed",
            "plumbing_rough_in":   "Plumbing pipes roughed in and visible in open wall or floor cavities before drywall",
            "low_voltage_wiring":  "Low voltage wiring visible — data, cable, security, or audio wiring roughed in",
            "insulation_complete": "Insulation installed and visible in wall and ceiling cavities before drywall",
        }
    },
    5: {
        "name": "Finished Building",
        "elements": {
            "all_finishes_complete": "All interior finish work visibly complete — trim, millwork, and finish surfaces done throughout",
            "flooring_installed":    "Final flooring installed throughout — hardwood, tile, carpet, or similar",
            "paint_complete":        "Interior and exterior paint visibly complete throughout",
            "fixtures_installed":    "Plumbing and electrical fixtures installed — sinks, toilets, light fixtures, outlets, and covers",
            "appliances_in_place":   "Kitchen and laundry appliances installed and in place",
        }
    },
}

ALL_ELEMENTS = [
    {
        "element":     el,
        "description": desc,
        "stage":       stage_num,
        "stage_name":  info["name"],
    }
    for stage_num, info in STAGE_TAXONOMY.items()
    for el, desc in info["elements"].items()
]

ELEMENT_KEYS = [item["element"] for item in ALL_ELEMENTS]

CRITICAL_ELEMENTS = {
    "slab_poured",
    "frame_standing",
    "roof_complete",
    "electrical_rough_in",
    "plumbing_rough_in",
    "hvac_installed",
}