# -*- coding: utf-8 -*-
"""Taxonomy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNUc8awrjRlg2jgCbwXKT20FeS1Fq5s0
"""

STAGE_TAXONOMY = {
    1: {
        "name": "Raw Land",
        "elements": {
            "undeveloped_property":  "",
            "no_utilities":          "",
            "no_improvements":       "",
        }
    },
    2: {
        "name": "Developed Land",
        "elements": {
            "demolition_clearing_grubbing": "",
            "grading":                      "Prepared soil graded and leveled for construction",
            "utilities_installed":          "Utility connections visible — electrical meters, water lines, gas meters, sewer caps, or utility trenches",
            "drainage_systems":             "",
            "parking_driveways":            "",
            "fencing":                      "",
        }
    },
    3: {
        "name": "Dried-In Building",
        "elements": {
            "slab_poured":              "Concrete foundation slab covering the full building footprint — not driveways or walkways",
            "frame_standing":           "",
            "roof_complete":            "",
            "windows_installed":        "",
            "exterior_doors_installed": "",
            "exterior_cladding":        "",
        }
    },
    4: {
        "name": "Pre-Sheetrock",
        "elements": {
            "electrical_rough_in": "Electrical wiring and boxes visible in open wall cavities before drywall",
            "hvac_installed":      "",
            "plumbing_rough_in":   "Plumbing pipes visible in open wall or floor cavities before drywall",
            "low_voltage_wiring":  "",
            "insulation_complete": "Insulation installed in all wall and ceiling cavities",
        }
    },
    5: {
        "name": "Finished Building",
        "elements": {
            "all_finishes_complete": "",
            "flooring_installed":    "",
            "paint_complete":        "",
            "fixtures_installed":    "Plumbing and electrical fixtures installed — sinks, toilets, light fixtures, outlets, and covers",
            "appliances_in_place":   "",
        }
    },
}

ALL_ELEMENTS = [
    {
        "element":     el,
        "description": desc,
        "stage":       stage_num,
        "stage_name":  info["name"],
    }
    for stage_num, info in STAGE_TAXONOMY.items()
    for el, desc in info["elements"].items()
]

ELEMENT_KEYS = [item["element"] for item in ALL_ELEMENTS]